services:
  swim-app:
    container_name: swim-app
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./.env.local
    volumes:
      - ./:/app/
      - /app/node_modules
  local-db:
    container_name: local-db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local
      - POSTGRES_DB=local
      - PGPORT=5001
    ports:
      - "5001:5001"
    volumes:
      - /databases/core-db:/var/lib/postgresql/data
