name: Playwright Tests
on:
  pull_request:
    branches: [main, master]
jobs:
  teste2e:
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: local
          POSTGRES_USER: local
          POSTGRES_DB: local
          PGPORT: 6543
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6543:6543
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://local:local@localhost:6543/local
      AUTH0_SECRET: ${{ secrets.AUTH0_SECRET }}
      AUTH0_BASE_URL: http://localhost:3000
      AUTH0_ISSUER_BASE_URL: ${{ secrets.AUTH0_ISSUER_BASE_URL }}
      AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
      AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      AUTH0_MANAGEMENT_API_CLIENT_ID: ${{ secrets.AUTH0_MANAGEMENT_API_CLIENT_ID }}
      AUTH0_MANAGEMENT_API_CLIENT_SECRET: ${{ secrets.AUTH0_MANAGEMENT_API_CLIENT_SECRET }}
      TEST_USER: ${{ secrets.TEST_USER }}
      TEST_PASS: ${{ secrets.TEST_PASS }}
      DISABLE_ERD: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.1.0
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate API Client
        run: yarn prisma generate
      - name: Create tables
        run: yarn prisma migrate deploy
      - name: Get AUTH0 TMP Token
        run: |
          echo "Enabling script to execute"
          chmod +x ./scripts/migrate.sh
          echo "migrating auth0 users..."
          response=$(curl --request POST \
            --url $AUTH0_ISSUER_BASE_URL/oauth/token \
            --header 'content-type: application/json' \
            --data "{\"client_id\":\"$AUTH0_MANAGEMENT_API_CLIENT_ID\",\"client_secret\":\"$AUTH0_MANAGEMENT_API_CLIENT_SECRET\",\"audience\":\"https://dev-uw0vq8v32kjv4k1a.us.auth0.com/api/v2/\",\"grant_type\":\"client_credentials\"}")
          token=$(echo $response | jq -r '.access_token')
          echo "AUTH0_TMP_API_TOKEN=${token}" >> $GITHUB_ENV
      - name: Migrate Data
        run: yarn migrate:data
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
