name: Test
on:
  pull_request:
    branches: [main, master]
jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: local
          POSTGRES_DB: local
          PGPORT: 6543
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6543:6543
    env:
      DATABASE_URL: postgresql://local:local@localhost:6543/local
      DISABLE_ERD: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build + Generate API Client
        run: yarn build
      - name: Test
        run: yarn test:all
